package taskschedulingsimgui;

import javax.swing.DefaultListModel;

/**
 *
 * @author Ljubo Raicevic <rljubo90@gmail.com>
 */
public class DAddFreqTable extends javax.swing.JDialog {

    public String table = "";
    
    /**
     * Creates new form DAddFreqTable
     */
    public DAddFreqTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lTable.setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lTable = new javax.swing.JList();
        btnOK = new javax.swing.JButton();
        btnAddEntry = new javax.swing.JButton();
        btnRemoveEntry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(lTable);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnAddEntry.setText("Add Entry");
        btnAddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEntryActionPerformed(evt);
            }
        });

        btnRemoveEntry.setText("Remove Entry");
        btnRemoveEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddEntry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveEntry)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEntryActionPerformed
        if (lTable.getModel().getSize() > 0) {
            DefaultListModel dlm = (DefaultListModel) lTable.getModel();
            dlm.removeElementAt(lTable.getSelectedIndex());
        }
    }//GEN-LAST:event_btnRemoveEntryActionPerformed

    private void btnAddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEntryActionPerformed
        DAddEntryToFreqTable daetft = new DAddEntryToFreqTable(null, true);
        daetft.setLocationRelativeTo(this);
        daetft.setVisible(true);
        if (!daetft.value.isEmpty() && !daetft.probability.isEmpty()) {
            addEntry(daetft.value, daetft.probability);
        }
    }//GEN-LAST:event_btnAddEntryActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        DefaultListModel dlm = (DefaultListModel)lTable.getModel();
        StringBuilder sb = new StringBuilder();
        sb.append(dlm.size()).append(" ");
        
        for (int iCount = 0; iCount < dlm.getSize(); iCount++) {
            sb.append(dlm.getElementAt(iCount));
        }
        sb.deleteCharAt(sb.length() - 1); //remove space in the end
        table = sb.toString();
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void addEntry(String pEntry, String pProbability) {
        DefaultListModel dlm = (DefaultListModel)lTable.getModel();
        dlm.addElement(pEntry + " " + pProbability + " ");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEntry;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRemoveEntry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lTable;
    // End of variables declaration//GEN-END:variables
}
