package taskschedulingsimgui;

/**
 *
 * @author Ljubo Raicevic <rljubo90@gmail.com>
 */
public class DAddTask extends javax.swing.JDialog {

    public String task = "";
    
    /**
     * Creates new form DAddFixedTask
     */
    public DAddTask(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmDeadlinePopup = new javax.swing.JPopupMenu();
        pmpdFixed = new javax.swing.JMenuItem();
        pmdpUniform = new javax.swing.JMenuItem();
        pmdpFreqTable = new javax.swing.JMenuItem();
        pmExeTimePopup = new javax.swing.JPopupMenu();
        pmetpFixed = new javax.swing.JMenuItem();
        pmetpUniform = new javax.swing.JMenuItem();
        pmetpFreqTable = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        tfTaskName = new javax.swing.JTextField();
        spnPhase = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddTask = new javax.swing.JButton();
        tfDeadline = new javax.swing.JTextField();
        tfExeTime = new javax.swing.JTextField();
        btnDeadlineProperties = new javax.swing.JButton();
        btnExeTimeProperties = new javax.swing.JButton();
        spnPeriod = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        pmDeadlinePopup.setInvoker(btnDeadlineProperties);
        pmDeadlinePopup.setName(""); // NOI18N

        pmpdFixed.setText("Add Fixed Deadline");
        pmpdFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmpdFixedActionPerformed(evt);
            }
        });
        pmDeadlinePopup.add(pmpdFixed);

        pmdpUniform.setText("Add Uniformly Random Deadline");
        pmdpUniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmdpUniformActionPerformed(evt);
            }
        });
        pmDeadlinePopup.add(pmdpUniform);

        pmdpFreqTable.setText("Add Deadline with Frequency Table");
        pmdpFreqTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmdpFreqTableActionPerformed(evt);
            }
        });
        pmDeadlinePopup.add(pmdpFreqTable);

        pmetpFixed.setText("Add Fixed Execution Time");
        pmetpFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmetpFixedActionPerformed(evt);
            }
        });
        pmExeTimePopup.add(pmetpFixed);

        pmetpUniform.setText("Add Uniformly Random Execution Time");
        pmetpUniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmetpUniformActionPerformed(evt);
            }
        });
        pmExeTimePopup.add(pmetpUniform);

        pmetpFreqTable.setText("Add Execution Time with Frequency Table");
        pmetpFreqTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmetpFreqTableActionPerformed(evt);
            }
        });
        pmExeTimePopup.add(pmetpFreqTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Task");
        setResizable(false);

        jLabel1.setText("Task name:");

        tfTaskName.setText("unnamed_task");

        spnPhase.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel2.setText("Initial phase:");

        jLabel3.setText("Deadline:");

        jLabel4.setText("Execution time:");

        btnAddTask.setText("Add task");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        tfDeadline.setEditable(false);
        tfDeadline.setText("FIXED 1");

        tfExeTime.setEditable(false);
        tfExeTime.setText("FIXED 1");

        btnDeadlineProperties.setText("Right click to set");
        btnDeadlineProperties.setComponentPopupMenu(pmDeadlinePopup);

        btnExeTimeProperties.setText("Right click to set");
        btnExeTimeProperties.setComponentPopupMenu(pmExeTimePopup);

        spnPeriod.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnPeriod.setValue(1);

        jLabel5.setText("Period:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(tfExeTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExeTimeProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(btnDeadlineProperties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tfTaskName)
                    .addComponent(spnPhase, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spnPeriod))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnDeadlineProperties))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfExeTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnExeTimeProperties))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTask)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        task = tfTaskName.getText() + " "
                + spnPhase.getValue().toString() + " "
                + tfDeadline.getText() + " "
                + spnPeriod.getValue().toString() + " "
                + tfExeTime.getText();
        
        this.dispose();
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void pmpdFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmpdFixedActionPerformed
        DAddFixed daf = new DAddFixed(null, true);
        daf.setLocationRelativeTo(this);
        daf.setVisible(true);
        if (!daf.value.isEmpty()) {
            addFixedDeadline(daf.value);
        }
    }//GEN-LAST:event_pmpdFixedActionPerformed

    private void pmdpUniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmdpUniformActionPerformed
        DAddUniform dau = new DAddUniform(null, true);
        dau.setLocationRelativeTo(this);
        dau.setVisible(true);
        if (!dau.minValue.isEmpty() && !dau.maxValue.isEmpty()) {
            addUniformDeadline(dau.minValue, dau.maxValue);
        }
    }//GEN-LAST:event_pmdpUniformActionPerformed

    private void pmdpFreqTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmdpFreqTableActionPerformed
        DAddFreqTable daft = new DAddFreqTable(null, true);
        daft.setLocationRelativeTo(this);
        daft.setVisible(true);
        if (!daft.table.isEmpty()) {
            addFreqTableDeadline(daft.table);
        }
    }//GEN-LAST:event_pmdpFreqTableActionPerformed

    private void pmetpFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmetpFixedActionPerformed
        DAddFixed daf = new DAddFixed(null, true);
        daf.setLocationRelativeTo(this);
        daf.setVisible(true);
        if (!daf.value.isEmpty()) {
            addFixedExeTime(daf.value);
        }
    }//GEN-LAST:event_pmetpFixedActionPerformed

    private void pmetpUniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmetpUniformActionPerformed
        DAddUniform dau = new DAddUniform(null, true);
        dau.setLocationRelativeTo(this);
        dau.setVisible(true);
        if (!dau.minValue.isEmpty() && !dau.maxValue.isEmpty()) {
            addUniformExeTime(dau.minValue, dau.maxValue);
        }
    }//GEN-LAST:event_pmetpUniformActionPerformed

    private void pmetpFreqTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmetpFreqTableActionPerformed
        DAddFreqTable daft = new DAddFreqTable(null, true);
        daft.setLocationRelativeTo(this);
        daft.setVisible(true);
        if (!daft.table.isEmpty()) {
            addFreqTableExeTime(daft.table);
        }
    }//GEN-LAST:event_pmetpFreqTableActionPerformed
    
    private void addFixedDeadline(String value) {
        tfDeadline.setText("FIXED " + value);
    }
    
    private void addUniformDeadline(String min, String max) {
        tfDeadline.setText("MIN_MAX_UNIFORM " + min + " " + max + " 0");
    }
    
    private void addFreqTableDeadline(String table) {
        tfDeadline.setText("FREQUENCY_TABLE " + table);
    }
    
    private void addFixedExeTime(String value) {
        tfExeTime.setText("FIXED " + value);
    }
    
    private void addUniformExeTime(String min, String max) {
        tfExeTime.setText("MIN_MAX_UNIFORM " + min + " " + max + " 0");
    }
    
    private void addFreqTableExeTime(String table) {
        tfExeTime.setText("FREQUENCY_TABLE " + table);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnDeadlineProperties;
    private javax.swing.JButton btnExeTimeProperties;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu pmDeadlinePopup;
    private javax.swing.JPopupMenu pmExeTimePopup;
    private javax.swing.JMenuItem pmdpFreqTable;
    private javax.swing.JMenuItem pmdpUniform;
    private javax.swing.JMenuItem pmetpFixed;
    private javax.swing.JMenuItem pmetpFreqTable;
    private javax.swing.JMenuItem pmetpUniform;
    private javax.swing.JMenuItem pmpdFixed;
    private javax.swing.JSpinner spnPeriod;
    private javax.swing.JSpinner spnPhase;
    private javax.swing.JTextField tfDeadline;
    private javax.swing.JTextField tfExeTime;
    private javax.swing.JTextField tfTaskName;
    // End of variables declaration//GEN-END:variables
}
