package taskschedulingsimgui;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ljubo Raicevic <rljubo90@gmail.com>
 */
public class DSimulation extends javax.swing.JDialog {

    private final String directory;
    private final String algorithm;
    private final String type;
    private final String repetitions;
    private Timer t;
    
    /**
     * Creates new form DSimulation
     */
    public DSimulation(
            java.awt.Frame parent, 
            boolean modal,
            String directory,
            String algorithm,
            String type,
            String repetitions) {
        super(parent, modal);
        
        this.directory = directory;
        this.algorithm = algorithm;
        this.type = type;
        this.repetitions = repetitions;
        
        initComponents();
        
        lblRepetitions.setText("/" + repetitions);
        deleteFilesFromTraceDir();
        
        t = new Timer();
        t.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                lTraceFiles.setModel(getTraceFiles());
                lblProgress.setText(Integer.toString(lTraceFiles.getModel().getSize()));
            }
        }, 0, 5000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lTraceFiles = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnStartSimulation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        lblRepetitions = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnStartInterval = new javax.swing.JSpinner();
        spnEndInterval = new javax.swing.JSpinner();
        cbShowDeadlines = new javax.swing.JCheckBox();
        btnDrawDiagram = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sldWidth = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simulation");

        taOutput.setColumns(20);
        taOutput.setRows(5);
        jScrollPane1.setViewportView(taOutput);

        jScrollPane2.setViewportView(lTraceFiles);

        jLabel1.setText("Trace files generated by simulations:");

        btnStartSimulation.setText("START SIMULATION");
        btnStartSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSimulationActionPerformed(evt);
            }
        });

        jLabel2.setText("<html>Combined result statistics for all repetitions of the simulation<br>\n(displayed when all repetitions of the simulation are finished):</html>");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Progress:");

        lblProgress.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblProgress.setText("0");

        lblRepetitions.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblRepetitions.setText("/repetitions");

        jLabel4.setText("Start of interval:");

        jLabel5.setText("End of interval:");

        spnStartInterval.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spnEndInterval.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(100), Integer.valueOf(100), null, Integer.valueOf(1)));

        cbShowDeadlines.setText("Show deadlines");

        btnDrawDiagram.setText("Draw Gantt Diagram for Selected Trace File");
        btnDrawDiagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawDiagramActionPerformed(evt);
            }
        });

        jLabel6.setText("Parameters for drawing Gantt diagram");

        sldWidth.setMaximum(30);
        sldWidth.setMinimum(2);

        jLabel7.setText("Time unit width:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnStartSimulation)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblProgress)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblRepetitions)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDrawDiagram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnEndInterval)
                                    .addComponent(spnStartInterval)
                                    .addComponent(sldWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbShowDeadlines, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartSimulation)
                    .addComponent(jLabel3)
                    .addComponent(lblProgress)
                    .addComponent(lblRepetitions))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spnStartInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnEndInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbShowDeadlines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDrawDiagram))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSimulationActionPerformed
        new Thread(new Runnable() {
            public void run() {
                taOutput.setText(executeSimulation(directory, algorithm, type, repetitions));
            }
        }).start();
    }//GEN-LAST:event_btnStartSimulationActionPerformed

    private void btnDrawDiagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawDiagramActionPerformed
        if ((int)spnEndInterval.getValue() > (int)spnStartInterval.getValue()
                && lTraceFiles.getSelectedIndex() != -1) {
            
            FGanttChart fgc = new FGanttChart(
                    null,
                    true,
                    "io/trace/" + lTraceFiles.getSelectedValue().toString(), 
                    (int)spnStartInterval.getValue(), 
                    (int)spnEndInterval.getValue(), 
                    32 - sldWidth.getValue(),
                    cbShowDeadlines.isSelected());

            fgc.setLocationRelativeTo(this);
            fgc.setVisible(true);
        }
    }//GEN-LAST:event_btnDrawDiagramActionPerformed

    private String executeSimulation(
            String dir, 
            String algorithm, 
            String type, 
            String repetitions) {
        
        StringBuilder output = new StringBuilder();
	Process p;
        
        deleteFilesFromTraceDir();
        
	try {
            String command = "java -jar " + System.getProperty("user.dir") 
                    + File.separator + "TaskSchedulingSimulator.jar 1 "  
                    + "SIMULATION " 
                    + algorithm + " " 
                    + type + " "
                    + repetitions; 
            
            p = Runtime.getRuntime().exec(command);
            p.waitFor();
            BufferedReader reader = 
                new BufferedReader(new InputStreamReader(p.getInputStream()));

            String line = "";			
            while ((line = reader.readLine())!= null) {
                    output.append(line).append("\n");
            }
            
        } catch (IOException | InterruptedException e) { }
        
        return output.toString();
    }
    
    private DefaultListModel getTraceFiles() {
        File traceDir = new File("io/trace");
        File[] files = traceDir.listFiles();
        Arrays.sort(files);
        
        DefaultListModel dlm = new DefaultListModel();
        for (File f: files) {
            dlm.addElement(f.getName());
        }
        
        return dlm;
    }
    
    private void deleteFilesFromTraceDir() {
        File traceDir = new File("io/trace");
        File[] files = traceDir.listFiles();
        for (File f: files) {
            f.delete();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrawDiagram;
    private javax.swing.JButton btnStartSimulation;
    private javax.swing.JCheckBox cbShowDeadlines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lTraceFiles;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblRepetitions;
    private javax.swing.JSlider sldWidth;
    private javax.swing.JSpinner spnEndInterval;
    private javax.swing.JSpinner spnStartInterval;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}